### ISSUE TITLE
Unable to install using pip

### ISSUE THREAD

**Issue by srikanthlogic** [Koodous/python-sdk#10]
Collecting koodous
  Downloading https://files.pythonhosted.org/packages/cb/42/283843089e1cf7cf3de882901339754b1a26c1f7e9ebb057c7d03c216d6d/koodous-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-r3dv9uw6/koodous/setup.py", line 11, in <module>
        long_description = open(readme_path, 'r').read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 2581: ordinal not in range(128)
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
        from apport.packaging_impl import impl as packaging
      File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
        import apt
      File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
        import apt_pkg
    ImportError: No module named 'apt_pkg'
    
    Original exception was:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-r3dv9uw6/koodous/setup.py", line 11, in <module>
        long_description = open(readme_path, 'r').read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 2581: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-r3dv9uw6/koodous/

**Comment by srikanthlogic** [comment]
Thanks for hint. I ran update-locale and was then subsequently able to install koodous successfully.

**Comment by Nekmo** [comment]
You are welcome :)
