### ISSUE TITLE
Cannot install koodous-py

### ISSUE THREAD

**Issue by zyrikby** [Koodous/python-sdk#5]
Hi,
I try to install koodous-py library, but I get the following error:
```bash
pip install koodous-py       
Collecting koodous-py
  Using cached https://files.pythonhosted.org/packages/71/a8/c8e6a6f8ea900296082e1d395a219fbcbf30304ab1db802ea3621f123f98/koodous-py-0.8.tar.gz
Collecting click==6.2 (from koodous-py)
  Using cached https://files.pythonhosted.org/packages/a0/90/0f5ea412a4d5b8e31cb514208e02824b45a8f4de52654733f0a862353fd9/click-6.2-py2.py3-none-any.whl
Collecting coloredlogs==5.0 (from koodous-py)
  Using cached https://files.pythonhosted.org/packages/d2/55/309a63bb40192cc2e7f4da7c12eaf4ca461e5ff970c9c86378747d0996f3/coloredlogs-5.0.tar.gz
Collecting humanfriendly==1.42 (from koodous-py)
  Using cached https://files.pythonhosted.org/packages/d3/09/d515827544b177921de9d9d96e0f3222618801d068c0aa3504aa8732858c/humanfriendly-1.42.tar.gz
Collecting Pygments==2.0.2 (from koodous-py)
  Using cached https://files.pythonhosted.org/packages/87/e3/cadb43a197476ec0adef73292ea7ea188f2b0531188eebc150905d3ed78c/Pygments-2.0.2-py3-none-any.whl
Collecting requests==2.8.1 (from koodous-py)
  Using cached https://files.pythonhosted.org/packages/c0/0f/a911a44c89ba01b23d8fe3defbdfca1e962de6f11a11da32658902cdc2a4/requests-2.8.1-py2.py3-none-any.whl
Collecting androguard==3.0 (from koodous-py)
  Using cached https://files.pythonhosted.org/packages/6b/14/beef9e3f20e9b40ec5bc2133fe5a983501952452826746729c13f84433a9/androguard-3.0.tar.gz
Requirement already satisfied: certifi in ./.pyenv/versions/3.7.0/lib/python3.7/site-packages (from koodous-py) (2018.4.16)
Collecting distribute (from androguard==3.0->koodous-py)
  Using cached https://files.pythonhosted.org/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d_a5kl15/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/pip-install-d_a5kl15/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/pip-install-d_a5kl15/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/tmp/pip-install-d_a5kl15/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/pip-install-d_a5kl15/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/pip-install-d_a5kl15/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-d_a5kl15/distribute/
```

For Python management, I use pyenv. Here are the versions of Python and pip currently installed:

```bash
yury:~$ python --version
Python 3.7.0
yury:~$ pip --version
pip 18.0 from /home/yury/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pip (python 3.7)

```

Could you please help me to resolve this issue?

**Comment by Nekmo** [comment]
Hi, this library is probably for Python 2.7. Have you tried using Python2?

**Comment by zyrikby** [comment]
HI @Nekmo!  Actually, I did not try, I thought it should work with Python 3.
Koodousers, can you confirm that this library is only for Python 2?

**Comment by Nekmo** [comment]
Maybe this library needs to be migrated to Python 3.x. I understand your frustration but in the meantime you can try using Python2.

**Comment by iantruslove** [comment]
Looking at the code, this library is indeed only for Python 2. It does not currently work with Python 3.

**Comment by Nekmo** [comment]
It's done, thanks :D
