### ISSUE TITLE
unit tests are broken

### ISSUE THREAD

**Issue by iantruslove** [Koodous/python-sdk#6]
The unit tests fail:

```sh
python tests/unit_tests.py $MY_KOODOUS_TOKEN

66753c1dccb9bd650ae3710d4efb326b62cde320dba26b3a3c88906b9bf9145a

..Voting this APK: 66753c1dccb9bd650ae3710d4efb326b62cde320dba26b3a3c88906b9bf9145a
..FF.....
======================================================================
FAIL: test_search (__main__.TestKoodousSDK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_tests.py", line 118, in test_search
    self.assertTrue(len(apks) > 0)
AssertionError: False is not true

======================================================================
FAIL: test_analysis (__main__.TestKoodousSDK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_tests.py", line 129, in test_analysis
    analysis)).hexdigest() == '63717947c7e74150f71f5623d5b0318c')
AssertionError: False is not true

----------------------------------------------------------------------
Ran 11 tests in 31.546s

FAILED (failures=2)
```

**Comment by Nekmo** [comment]
Thanks!
